default_platform :ios

platform :ios do

  before_all do
    puts "Doin' some fastlane..."
  end

  desc "Runs all the specs"
  lane :specs do
    scan(scheme: "InstagramSimpleOAuth",
         clean: true,
         configuration: "Debug",
         output_style: "rspec",
         code_coverage: true)
  end

  desc "Take iPhone/iPad screenshots"
  lane :take_da_screenshots do
    snapshot
  end

  desc "Frame iPhone/iPad screenshots"
  lane :frame_da_screenshots do
    sh "cd ../Snapshots/"
    frameit(path: "Snapshots")
  end

  after_all do |lane|
    if lane.equal? :test
      puts "🌮 🌮 🌮  Taco Time! 🌮 🌮 🌮"
    end
  end

  error do |lane, exception|
    puts "uh oh...."
  end

end
